apiVersion: v1
kind: Pod
metadata:
  name: example-container
spec:
  #  activeDeadlineSeconds: 1800  # Pod terminates after 30 min
  securityContext:
    runAsUser: 237827 # run id command in terminal to get your UID
    runAsGroup: 50012
  containers:
    - name: example-container
      image: ghcr.io/sawyerczupka/d622_tmp:sha256-be8d5853dc059e515d91a2b388fdc2e0113f27e7441fe005cf7d27f75d504e4b.sig # image name
      resources:
        requests: # minimum resources
          memory: "16Gi"
          cpu: "8"
        limits: # maximum resources
          memory: "24Gi"
          cpu: "16"
      volumeMounts:
        - name: home
          mountPath: "/app"
      command: ["/bin/sh"]
      stdin: true
      tty: true
  volumes:
    - name: home
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/sczupka/git/
  imagePullSecrets:
    - name: ghcr-secret
